In [1]:
import pandas as pd
from spacy_dish_name_map import *
from similarity_map import *
from config import Baseconfig

In [2]:
config = Baseconfig()

df_dish = pd.read_csv(config.dish_path)
df = pd.read_csv(config.review_path)
if config.is_test:
    sampled_business_ids = df['business_id'].sample(n=3, random_state=123).tolist()
    df = df[df['business_id'].isin(sampled_business_ids)]
df['text_clean'] = df['text'].apply(clean_text)

In [3]:
ACTION_VERBS = get_action_verbs(df, 'text_clean', 20)
filtered_df = df_dish[df_dish['last_appeared'] > 2000]
# Extract the names into a list
MENUE_ITEMS = filtered_df['name'].tolist()

In [4]:
df['matched_items'] = df['text'].apply(lambda x: map_by_cosine_similarity(x, MENUE_ITEMS))

In [5]:
test_df = apply_spacy_to_df(df, ACTION_VERBS, MENUE_ITEMS, True, 3)

In [6]:
test_df.head(5)

,business_id,date,review_id,stars,text,type,user_id,cool,useful,funny,text_clean,matched_items,dishes_raw,dishes_lemmatized,filtered_dishes,valid_dishes
81,5kRug3bEienrpovtPRVVwg,2012-06-29,BslISEau8Pk2voEPN7kY-g,4,Rokerij is worth the hype. We popped in last w...,review,gcyEUr4DXcbjnGRAWFtfAQ,0,1,0,rokerij is worth the hype we popped in last we...,"[Potatoes, Chardonnay, Glass Mountain, Curried...","[a beer, some potato, the side, awesome wifey,...","[a beer, some potato, the side, awesome wifey,...",[],[]
445,6Lo25bdGe3qEdFLGygBsPw,2011-08-21,qbw_6lX5pyM7YBWxHrBbbw,5,"Like others, I found this studio through a Liv...",review,Y_iCmH_z_T5cOy3_8p_pQw,2,2,0,like others i found this studio through a livi...,[],"[a small studio, this studio, a live social co...","[a small studio, this studio, a live social co...",[],[]
2120,5kRug3bEienrpovtPRVVwg,2011-10-30,LWob6jdkvZa_aGsifYQLEw,2,I was expecting more since there are so many 5...,review,28i9BnGOUpL4z4HJC18gfg,0,1,2,i was expecting more since there are so many 5...,"[Beans, Cheese Plate, Clams, la piece, Cup Con...","[dog food, the middle, my husband plate, three...","[dog food, the middle, my husband plate, three...",[],[]
2656,km3g-wDO2KfhfnTvJrLJig,2011-02-24,v1EPSrG6zRUhd41Jt2ZTHA,3,Last night after developing a huge craving for...,review,1uwqR1r9nMDgI6RZT_bL2w,0,0,0,last night after developing a huge craving for...,"[Bell Pepper Crudites, Cocktail Sauce, 1/2 Chi...","[a bit, the fact, my food, another order I be ...","[a bit, the fact, my food, another order I be ...",[],[]
4617,5kRug3bEienrpovtPRVVwg,2011-09-22,cfOrdnJ9zvnc7azAXHiXJA,4,Very good food. Our service was great--thank ...,review,ut3yURTCq7V5alsWUksEjg,0,3,0,very good food our service was greatthank you...,[],"[some good wine and food recommendation, very ...","[some good wine and food recommendation, very ...",[],[]